version = 0.1
[default.deploy.parameters]
stack_name = "sota-watchtower-stack"
tags = "project=\"sota-watchtower\""
resolve_s3 = true
s3_prefix = "sota-watchtower-stack"
region = "eu-central-1"
capabilities = "CAPABILITY_IAM"
image_repositories = []
parameter_overrides =[
	"TelegramBotToken=7083724126:AAFKp9Ntmv6gErZEmVAQJNktImxTQd5pslM",
    "TelegramUserChatId=5861279366",
    "TelegramGroupChatId=-1002179601871",
	"FrequencyFilterPattern=\\b(145|433|2|70).*-.*\\b"
	]